# Generated by Django 2.1.4 on 2020-02-29 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalmanagement',
            name='positions',
            field=models.FloatField(default=int, verbose_name='持仓股数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountsurplus',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 29, 20, 11, 6, 858389), verbose_name='结算日期'),
        ),
        migrations.AlterField(
            model_name='capitalaccount',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 29, 20, 11, 6, 857877), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='mystocklists',
            name='trade_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 29, 20, 11, 6, 864098), verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 29, 20, 11, 6, 861352), verbose_name='结算日起'),
        ),
        migrations.AlterField(
            model_name='tradedailyreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 29, 20, 11, 6, 860730), verbose_name='结算日期'),
        ),
        migrations.AlterField(
            model_name='tradelists',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 29, 20, 11, 6, 859373), verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='tradeperformance',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 29, 20, 11, 6, 860174), verbose_name='评价日期'),
        ),
    ]
