# Generated by Django 2.1.4 on 2020-05-07 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsurplus',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 10, 39, 14, 343641), verbose_name='结算日期'),
        ),
        migrations.AlterField(
            model_name='capitalaccount',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 10, 39, 14, 343102), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='monitorindustry',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 10, 39, 14, 353766), verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='mystocklists',
            name='trade_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 10, 39, 14, 350582), verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 10, 39, 14, 346544), verbose_name='结算日起'),
        ),
        migrations.AlterField(
            model_name='tradedailyreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 10, 39, 14, 345927), verbose_name='结算日期'),
        ),
        migrations.AlterField(
            model_name='tradelists',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 10, 39, 14, 344601), verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='tradeperformance',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 10, 39, 14, 345404), verbose_name='评价日期'),
        ),
    ]
