# Generated by Django 2.1.4 on 2020-03-14 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_management', '0002_auto_20200314_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatestocks',
            name='express_eps_rate',
        ),
        migrations.AddField(
            model_name='evaluatestocks',
            name='express_diluted_roe',
            field=models.FloatField(default=0, verbose_name='业绩快报---净资产收益率'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountsurplus',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 14, 22, 26, 18, 10693), verbose_name='结算日期'),
        ),
        migrations.AlterField(
            model_name='capitalaccount',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 14, 22, 26, 18, 9701), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='mystocklists',
            name='trade_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 14, 22, 26, 18, 22599), verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 14, 22, 26, 18, 16967), verbose_name='结算日起'),
        ),
        migrations.AlterField(
            model_name='tradedailyreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 14, 22, 26, 18, 16132), verbose_name='结算日期'),
        ),
        migrations.AlterField(
            model_name='tradelists',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 14, 22, 26, 18, 12566), verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='tradeperformance',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 14, 22, 26, 18, 14984), verbose_name='评价日期'),
        ),
    ]
